# run time changes
# volume bind
version: "3.2"
services:
  app:
    network_mode: "host"
    image: shadjachaudhari/nginx:mydemo
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf